server:
  port: 8080
  servlet:
    context-path: /

spring:
  application:
    name: mentora-backend
  datasource:
    # TiDB Cloud Serverless (MySQL-compatible)
    url: jdbc:mysql://gateway01.ap-southeast-1.prod.aws.tidbcloud.com:4000/mentora?sslMode=REQUIRED&enabledTLSProtocols=TLSv1.2,TLSv1.3&allowPublicKeyRetrieval=true
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: 3Q9njwBTT5gHaSW.root
    password: Fj7IWdxW7C2v5xNq
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: false
    properties:
      hibernate:
        format_sql: true

# JWT Security Configurations
mentora:
  app:
    jwtSecret: 404E635266556A586E3272357538782F413F4428472B4B6250645367566B5970
    jwtExpirationMs: 86400000 # 24 hours

# SpringDoc OpenAPI Documentation
springdoc:
  api-docs:
    path: /v3/api-docs
  swagger-ui:
    path: /swagger-ui.html
